languageCode = "ko"
languageName = "Korean"
weight = 1
# title = "ğ—Ÿğ—®ğ˜ğ—²ğ—¿ğ—¿ğ—² ğ—¦ğ—½ğ—®ğ—°ğ—²"
contentDir = "content/"

[params]
  displayName = "KO"
  isoCode = "ko"
  rtl = false
  dateFormat = "2006 January 02"
  logo = "img/laterre_logo_symbol.png"
  secondaryLogo = "img/laterre_logo_color.png"
  description = "Develop Experience @Backend Developer"
  copyright = "Â© { year } Laterre.dev"

[author]
  name = "Changil.Kim"
  image = "img/laterre_logo.png"
  headline = "Develop Experience @Backend Developer"
  bio = "ì¢‹ì€ ê°œë°œ ê²½í—˜ì´ë€ ë¬´ì—‡ì¼ì§€ í•­ìƒ ê³ ë¯¼í•©ë‹ˆë‹¤."
  links = [
    { github = "https://github.com/laterre39" },
    { stack-overflow = "https://stackoverflow.com/users/20004273/laterre" },
    { x-twitter = "https://twitter.com" },
    { email = "mailto:laterre39@naver.com" },
  ]

  