languageCode = "en"
languageName = "English"
weight = 2
title = "ğ‹ğ€ğ“ğ„ğ‘ğ‘ğ„ ğğ‹ğğ†"
contentDir = "content/"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/laterre_logo_symbol.png"
  secondaryLogo = "img/laterre_logo_color.png"
  description = "Develop Experience @Backend Developer"
  copyright = "Â© { year } Laterre.dev"

[author]
  name = "LATERRE"
  image = "img/laterre_logo.png"
  headline = "Develop Experience @Backend Developer"
  bio = "ì¢‹ì€ ê°œë°œ ê²½í—˜ì´ë€ ë¬´ì—‡ì¼ì§€ í•­ìƒ ê³ ë¯¼í•©ë‹ˆë‹¤."
  links = [
    { email = "mailto:laterre39@naver.com" },
    { x-twitter = "https://twitter.com" },
    { github = "https://github.com/laterre39" },
  ]

  